SELECT NOW();

SELECT CURRENT_DATE;

SELECT CURRENT_TIME;

SELECT CURRENT_TIMESTAMP;

SELECT TIMEOFDAY();

SELECT DATE_PART('month', NOW());

SELECT EXTRACT(YEAR FROM CURRENT_DATE);

SELECT AGE(CURRENT_DATE, DATE '2000-08-06');


SELECT * FROM empl_1;


SELECT EXTRACT(YEAR FROM joining_date) FROM empl_1;

SELECT EXTRACT(MONTH FROM joining_date) FROM empl_1;

SELECT EXTRACT(DAY FROM joining_date) FROM empl_1;


SELECT 
    EXTRACT(YEAR FROM CURRENT_DATE) AS year,
    EXTRACT(MONTH FROM CURRENT_DATE) AS month,
    EXTRACT(DAY FROM CURRENT_DATE) AS day,
    EXTRACT(DOW FROM CURRENT_DATE) AS day_of_week;



